version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      tiptap:
        patterns: ['@tiptap/*']
      univer:
        patterns: ['@univerjs/*']
  - package-ecosystem: gomod
    directory: /relay
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
